<!DOCTYPE html>
<html  lang="EN">	
	<head>
		<title>Les joies de la Wild Code School</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="style.css">
		<meta charset="utf-8">
	</head>
	
	<body>
		
	</body>
	
</html>